# Generated by Django 2.1.2 on 2019-01-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ddate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='published')),
            ],
        ),
        migrations.CreateModel(
            name='Ddiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=50)),
                ('dcontent', models.TextField()),
                ('ddate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Ddate')),
            ],
        ),
    ]
